//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DF.Business.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public long ErrorId { get; set; }
        public string ErrorMessage { get; set; }
        public string Error_LineNo { get; set; }
        public string Procedure_Name { get; set; }
        public string Method { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
